// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_50_lines = "CgkI4N33hM0WEAIQCA"; // <GPGSID>
        public const string leaderboard_high_scores = "CgkI4N33hM0WEAIQDA"; // <GPGSID>
        public const string achievement_10000_blocks = "CgkI4N33hM0WEAIQBg"; // <GPGSID>
        public const string achievement_1000_blocks = "CgkI4N33hM0WEAIQBQ"; // <GPGSID>
        public const string achievement_200_lines = "CgkI4N33hM0WEAIQCQ"; // <GPGSID>
        public const string achievement_triple = "CgkI4N33hM0WEAIQCg"; // <GPGSID>
        public const string achievement_100_blocks = "CgkI4N33hM0WEAIQBA"; // <GPGSID>
        public const string achievement_pentaline = "CgkI4N33hM0WEAIQCw"; // <GPGSID>
        public const string achievement_first_of_many = "CgkI4N33hM0WEAIQBw"; // <GPGSID>
        public const string leaderboard_high_scores_old = "CgkI4N33hM0WEAIQAQ"; // <GPGSID>

}

