default_platform(:android)

platform :android do
  desc "Upload signed AAB to Google Play"
  lane :deploy do |options|
    upload_to_play_store(
      aab: options[:aab_path],
      package_name: options[:package_name],
      track: options[:track],
      release_status: options[:release_status],
      json_key: options[:json_key_path],
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_changelogs: true
    )
  end
end
